/* Generated by restful-react */

export const SPEC_VERSION = "0.0.1";
export interface Country {
  id: number;
  name: string;
  iso3: string;
  iso2: string;
  phone_code: string;
  capital: string;
  currency: string;
  currency_symbol: string;
  tld: string;
  native: string | null;
  region: string;
  subregion: string;
  timezones: {
    zoneName: string;
    gmtOffset: number;
    gmtOffsetName: string;
    abbreviation: string;
    tzName: string;
  }[];
  translations: {
    br: string;
    pt: string;
    nl: string;
    hr: string;
    fa: string;
    de: string;
    es: string;
    fr: string;
    ja: string;
    it: string;
  } | null;
  latitude: string;
  longitude: string;
  emoji: string;
  emojiU: string;
}

export interface GeneralError {
  error?: string;
}

/**
 * Country list response
 */
export interface CountriesResponse {
  data: Country[];
}

/**
 * Validation error
 */
export type ValidationErrorResponse = GeneralError;

/**
 * Server error
 */
export type ServerErrorResponse = GeneralError;

export interface GetCountriesQueryParams {
  /**
   * Search string to filter to matching countries only
   */
  q?: string;
  /**
   * Page number
   */
  page?: number;
  /**
   * Number of records per page
   */
  pageSize?: number;
  /**
   * Adds a delay of x milliseconds to the response
   */
  latency?: number;
  /**
   * If set, will return a 500 error with a 50% probability
   */
  monkey?: string;
}
